### ISSUE TITLE
./remap.py: no such file or directory

### ISSUE THREAD

**Issue by isaacMedina1** [david0/durgod-keymapper#1]
System: 10.14.5 macOS Mojave, Intel Core i7. MacBook Pro 13-inch, Mid 2012

pip version: 20.3.1

Following the installation process described on README.md I get the line:

`-bash: ./remap.py: No such file or directory`

This was my last console print after uninstalling, getting wheel and reinstall: 

Collecting hidapi
  Using cached hidapi-0.10.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting setuptools>=19.0
  Downloading setuptools-50.3.2-py3-none-any.whl (785 kB)
     |...| 785 kB 601 kB/s 
Installing collected packages: setuptools, hidapi
Successfully installed hidapi-0.10.1 setuptools-50.3.2

Problem persists.

Suggestion: README.md may be better written, with a more descriptive process on installation or requirements.

**Comment by david0** [comment]
Hi,
I guess you are not so experienced in usage of shell, so a more detailed set of instructions would be:

[Install git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)

clone using 
```
git clone https://github.com/david0/durgod-keymapper.git
```
change into cloned directory using
```
cd durgod-keymapper
```

run script using 
```
./remap.py keymaps/taurus_k320 
```

**Comment by isaacMedina1** [comment]
Thank you, these detailed instructions solved my issue. And yes, I'm not that experienced as I began learning the shell just a few months ago. Thanks again for replying and sharing this awesome workaround!

**Comment by david0** [comment]
You're welcome!
