### ISSUE TITLE
keycode dictionary

### ISSUE THREAD

**Issue by mechtronsystems** [david0/durgod-keymapper#4]
Hello David, thanks for your utility.  I've been using the k320 for a while and I love it.  There have been some problems with the remapping program from durgod, when I remap the dash/underscore key it loses the underscore and has dash normal and shifted.  Anyway I wanted to try your utility and create a dvorak key map.
I noticed in the key map and source code that 'Roll' appears twice.  
KEYNAMES[0x47] = 'Roll'
KEYNAMES[0x48] = 'Roll'

Is this correct?  
thanks
Marko

**Comment by david0** [comment]
Hi, thank you. Should be fixed now.
